[manifest]
version = "1.0.0"
dump_lua = true
priority = -1

# Apply booster pack edition and stickers to contents - by Jen Walter
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "card.T.x = self.T.x"
position = "before"
payload = '''
local edi = self.edition or {}
if edi.type then
	if card.ability.name ~= "cry-meteor"
 	and card.ability.name ~= "cry-exoplanet"
  	and card.ability.name ~= "cry-stardust" then
		card:set_edition({[edi.type] = true})
  	end
end
local stickers = {'eternal', 'perishable', 'rental', 'banana'}
for _, v in ipairs(stickers) do
	if self.ability[v] then
		card.ability[v] = self.ability[v]
	end
end
if self.pinned then
	card.pinned = self.pinned
end
'''
match_indent = true

# save ability (to deal with re-misprinting)
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "G.vouchers:emplace(card_to_save)"
position = "before"
payload = '''
card_to_save.ability.extra = self and self.ability.extra or card_to_save.ability.extra
'''
match_indent = true



# don't draw old perishable texture
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''if self.ability.perishable then'''
position = "at"
payload = '''if self.ability.perishable and not layer then'''
match_indent = true

# Adds cry_debuff_immune card modifier
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = 'if self.ability and self.ability.perma_debuff then self.debuff = true end'
position = "after"
payload = '''
if self.cry_debuff_immune then
	self.debuff = false
end
'''
match_indent = true

# Removes cry_debuff_immune at the end of the round
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = 'for i = 1, #G.jokers.cards do'
position = "before"
payload = '''
for i = 1, #G.playing_cards do
	local CARD = G.playing_cards[i]
    CARD.cry_debuff_immune = false
end
'''
match_indent = true
